//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Climate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Climate()
        {
            this.Farm = new HashSet<Farm>();
            this.Soil = new HashSet<Soil>();
            this.TechnologicalOperations = new HashSet<TechnologicalOperations>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SummTempVegPer_5_10 { get; set; }
        public string SummTempVegPer_10_12 { get; set; }
        public string KolOsadkovJune { get; set; }
        public string KoefUvl { get; set; }
        public string DataBVegPer { get; set; }
        public string DataEVegPer { get; set; }
        public string KolOsadS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Farm> Farm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soil> Soil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechnologicalOperations> TechnologicalOperations { get; set; }
    }
}
