//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MehMach
    {
        public int Id { get; set; }
        public Nullable<int> Machinery_Id { get; set; }
        public Nullable<int> Mechanizator_Id { get; set; }
    
        public virtual Machinery Machinery { get; set; }
        public virtual Mechanizator Mechanizator { get; set; }
    }
}
