//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StamatDBEntities : DbContext
    {
        public StamatDBEntities()
            : base("name=StamatDBEntities")
        {
        }

        public StamatDBEntities(string ConnectionString)
            : base( ConnectionString )
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AdditionalPayments> AdditionalPayments { get; set; }
        public virtual DbSet<Agregates> Agregates { get; set; }
        public virtual DbSet<Breaking> Breaking { get; set; }
        public virtual DbSet<ClassMachine> ClassMachine { get; set; }
        public virtual DbSet<Climate> Climate { get; set; }
        public virtual DbSet<Cultures> Cultures { get; set; }
        public virtual DbSet<Disease> Disease { get; set; }
        public virtual DbSet<Farm> Farm { get; set; }
        public virtual DbSet<Fertilizer> Fertilizer { get; set; }
        public virtual DbSet<Him> Him { get; set; }
        public virtual DbSet<Intensification> Intensification { get; set; }
        public virtual DbSet<KindOfFuel> KindOfFuel { get; set; }
        public virtual DbSet<KindOfWork> KindOfWork { get; set; }
        public virtual DbSet<Machinery> Machinery { get; set; }
        public virtual DbSet<Mechanizator> Mechanizator { get; set; }
        public virtual DbSet<MehMach> MehMach { get; set; }
        public virtual DbSet<Pest> Pest { get; set; }
        public virtual DbSet<Predshest> Predshest { get; set; }
        public virtual DbSet<SickList> SickList { get; set; }
        public virtual DbSet<Soil> Soil { get; set; }
        public virtual DbSet<Sort> Sort { get; set; }
        public virtual DbSet<Stability> Stability { get; set; }
        public virtual DbSet<StakesOfMech> StakesOfMech { get; set; }
        public virtual DbSet<StakesOfWorkers> StakesOfWorkers { get; set; }
        public virtual DbSet<TechKart> TechKart { get; set; }
        public virtual DbSet<TechPacket> TechPacket { get; set; }
        public virtual DbSet<TKCosts> TKCosts { get; set; }
        public virtual DbSet<TkPayments> TkPayments { get; set; }
        public virtual DbSet<TKR> TKR { get; set; }
        public virtual DbSet<Trailers> Trailers { get; set; }
        public virtual DbSet<TypeSort> TypeSort { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WA_TKR> WA_TKR { get; set; }
        public virtual DbSet<WorkAreas> WorkAreas { get; set; }
        public virtual DbSet<TehAgro> TehAgro { get; set; }
        public virtual DbSet<TehAgroTO> TehAgroTO { get; set; }
        public virtual DbSet<TechnologicalOperations> TechnologicalOperations { get; set; }
        public virtual DbSet<OperationsOfAgregate> OperationsOfAgregate { get; set; }
    }
}
