//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationsOfAgregate
    {
        public int Id { get; set; }
        public float SeedingRate { get; set; }
        public float GSMCharge { get; set; }
        public Nullable<int> Agregates_Id { get; set; }
        public Nullable<int> TechnologicalOperations_Id { get; set; }
    
        public virtual Agregates Agregates { get; set; }
        public virtual TechnologicalOperations TechnologicalOperations { get; set; }
    }
}
