//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sort
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sort()
        {
            this.WA_TKR = new HashSet<WA_TKR>();
            this.Disease = new HashSet<Disease>();
            this.Pest = new HashSet<Pest>();
            this.Stability = new HashSet<Stability>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public float SeedingRase { get; set; }
        public float M1000 { get; set; }
        public float CountSeedOnGa { get; set; }
        public float Productivity { get; set; }
        public float ProductivityMax { get; set; }
        public int GrowingSeason_0 { get; set; }
        public int GrowingSeason_1 { get; set; }
        public Nullable<int> Cultures_Id { get; set; }
        public Nullable<int> Farm_Id { get; set; }
        public Nullable<int> TypeSort_Id { get; set; }
    
        public virtual Cultures Cultures { get; set; }
        public virtual Farm Farm { get; set; }
        public virtual TypeSort TypeSort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WA_TKR> WA_TKR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disease> Disease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pest> Pest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stability> Stability { get; set; }
    }
}
