//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechPacket
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Operations { get; set; }
        public Nullable<int> Intensification_Id { get; set; }
        public Nullable<int> Predshest_Id { get; set; }
        public Nullable<int> Cultures_Id { get; set; }
        public Nullable<int> Soil_Id { get; set; }
    
        public virtual Cultures Cultures { get; set; }
        public virtual Intensification Intensification { get; set; }
        public virtual Predshest Predshest { get; set; }
        public virtual Soil Soil { get; set; }
    }
}
