//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnologicalOperations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechnologicalOperations()
        {
            this.TechKart = new HashSet<TechKart>();
            this.Climate = new HashSet<Climate>();
            this.OperationsOfAgregate = new HashSet<OperationsOfAgregate>();
        }
    
        public int Id { get; set; }
        public string KodOperation { get; set; }
        public string Name { get; set; }
        public string Parametrs { get; set; }
        public string Annotation { get; set; }
        public string Application { get; set; }
        public string Unit { get; set; }
        public int Rang { get; set; }
        public Nullable<int> KindOfWork_Id { get; set; }
    
        public virtual KindOfWork KindOfWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechKart> TechKart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Climate> Climate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsOfAgregate> OperationsOfAgregate { get; set; }
    }
}
