//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechKart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechKart()
        {
            this.TKCosts = new HashSet<TKCosts>();
            this.TkPayments = new HashSet<TkPayments>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int TKR_Id { get; set; }
        public int WorkAreas_Id { get; set; }
        public int TechnologicalOperations_Id { get; set; }
    
        public virtual TKR TKR { get; set; }
        public virtual WorkAreas WorkAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKCosts> TKCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TkPayments> TkPayments { get; set; }
        public virtual TechnologicalOperations TechnologicalOperations { get; set; }
    }
}
