//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TkPayments
    {
        public int Id { get; set; }
        public Nullable<int> AdditionalPayments_Id { get; set; }
        public Nullable<int> TechKart_Id { get; set; }
    
        public virtual AdditionalPayments AdditionalPayments { get; set; }
        public virtual TechKart TechKart { get; set; }
    }
}
