//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trailers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trailers()
        {
            this.Agregates = new HashSet<Agregates>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public float Price { get; set; }
        public float NormZagruz { get; set; }
        public float PersentAmortOfTO { get; set; }
        public int Count { get; set; }
        public float PercentAmort { get; set; }
        public Nullable<int> Farm_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agregates> Agregates { get; set; }
        public virtual Farm Farm { get; set; }
    }
}
