//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_TKR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WA_TKR()
        {
            this.Pest = new HashSet<Pest>();
            this.Stability = new HashSet<Stability>();
            this.Disease = new HashSet<Disease>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Sort_Id { get; set; }
        public Nullable<int> TKR_Id { get; set; }
        public Nullable<int> WorkAreas_Id { get; set; }
    
        public virtual Sort Sort { get; set; }
        public virtual TKR TKR { get; set; }
        public virtual WorkAreas WorkAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pest> Pest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stability> Stability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disease> Disease { get; set; }
    }
}
