//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkAreas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkAreas()
        {
            this.TechKart = new HashSet<TechKart>();
            this.WA_TKR = new HashSet<WA_TKR>();
        }
    
        public int Id { get; set; }
        public int IdUch { get; set; }
        public string NumUch { get; set; }
        public float Square { get; set; }
        public float MaxShirZahv { get; set; }
        public double Lenght { get; set; }
        public double Wight { get; set; }
        public double Angle_gr { get; set; }
        public double KolokPercent { get; set; }
        public double Distanse { get; set; }
        public Nullable<int> Farm_Id { get; set; }
        public Nullable<int> Soil_Id { get; set; }
    
        public virtual Farm Farm { get; set; }
        public virtual Soil Soil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechKart> TechKart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WA_TKR> WA_TKR { get; set; }
    }
}
